# Generated by Django 5.0.1 on 2024-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtracted',
            fields=[
                ('extracted_from', models.CharField(default=' ', max_length=30)),
                ('domain', models.CharField(default=' ', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('white_list', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
            ],
        ),
    ]
