# Generated by Django 5.0.1 on 2024-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DataExtracted',
        ),
    ]
