# Generated by Django 5.0.1 on 2024-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0002_customuser_delete_dataextracted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='dni',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='first_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='last_name',
        ),
    ]
